language: cpp
sudo: required
dist: trusty
git:
  submodules: false
before_install:
  - export GCC_VERSION_MAJOR=4
  - export GCC_VERSION_MINOR=8
  - export GCC_VERSION_PATCH
  - export GCC_VERSION="${GCC_VERSION_MAJOR}.${GCC_VERSION_MINOR}"
  - export QT_VERSION_MAJOR=5
  - export QT_VERSION_MINOR=9
  - export QT_VERSION_PATCH
  - export QT_VERSION_MAJORMINOR="${QT_VERSION_MAJOR}${QT_VERSION_MINOR}"
  - export QT_VERSION_MAJORMINORPATCH="${QT_VERSION_MAJOR}${QT_VERSION_MINOR}${QT_VERSION_PATCH}"
  - export QT_VERSION="${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}.${QT_VERSION_PATCH}"
  - export CMAKE_VERSION_MAJOR=3
  - export CMAKE_VERSION_MINOR=8
  - export CMAKE_VERSION_PATCH=2
  - export CMAKE_VERSION="${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}.${CMAKE_VERSION_PATCH}"
  - export CMAKE_VERSION_MAJOR_DOT_MINOR="${CMAKE_VERSION_MAJOR}.${CMAKE_VERSION_MINOR}"
  - sudo add-apt-repository --yes ppa:beineri/opt-qt${QT_VERSION_MAJORMINORPATCH}-trusty
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-${GCC_VERSION} libsamplerate0-dev libquazip0-dev
  - sudo apt-get install -qq -y qt${QT_VERSION_MAJORMINOR}base qt${QT_VERSION_MAJORMINOR}declarative qt${QT_VERSION_MAJORMINOR}imageformats qt${QT_VERSION_MAJORMINOR}location qt${QT_VERSION_MAJORMINOR}multimedia qt${QT_VERSION_MAJORMINOR}quickcontrols qt${QT_VERSION_MAJORMINOR}script qt${QT_VERSION_MAJORMINOR}svg qt${QT_VERSION_MAJORMINOR}tools qt${QT_VERSION_MAJORMINOR}translations libsdl2-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${GCC_VERSION} 90
  - wget https://cmake.org/files/v${CMAKE_VERSION_MAJOR_DOT_MINOR}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh
  - chmod +x cmake-${CMAKE_VERSION}-Linux-x86_64.sh
  - mkdir cmake-bin
  - ./cmake-${CMAKE_VERSION}-Linux-x86_64.sh --skip-license --prefix=`pwd`/cmake-bin
script:
  - source /opt/qt${QT_VERSION_MAJORMINOR}/bin/qt${QT_VERSION_MAJORMINOR}-env.sh
  - mkdir phoenix-build
  - cd phoenix-build
  - ../cmake-bin/bin/cmake ..
  - make -j4
  - mkdir phoenix-out
  - cp Phoenix phoenix-out
  - cp -r Metadata phoenix-out
  - cp -r QML phoenix-out
  - wget "https://s3.amazonaws.com/travis-ci-gmbh/artifacts/stable/build/linux/amd64/artifacts" -O ../artifacts
  - chmod +x ../artifacts
  - export PATH=`pwd`/..:$PATH
  - cd phoenix-out
  - export BUILD_TAG="Phoenix-${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:6}-travis${TRAVIS_BUILD_NUMBER}-Linux"
  - artifacts upload --target-paths /Linux/${BUILD_TAG} --working-dir `pwd` .
notifications:
  irc:
    channels:
      - "chat.freenode.net#phoenix-dev"
    use_notice: true
    skip_join: true
