# Special thanks to MuseScore

language: cpp
sudo: false

env:
  global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - secure: "XMKxvHKgJmvcadiENukV02OG5OnUUF7+LmKOTkQk2Fxa1LMNQqSRncIC9G0qqdFQPqjVXhDM3aBFUTxTkTk7rlsT4LO1+XlgZ6B4QBo22GfhPcgjJaUqVMmjoMNINiO32ED4mi+dhLYr7ewnZCEijYxpA0sqRbUiM1l0fUZwiHk="
    - secure: "gLHgwDamFLrBVbb7LIiPgFhKmnNGLFTvsb0Dk146QS9LBtuYHDJRZbt1sv1ZC/704nCPk6zarqersRifcQAW46IaoW6sn+0UP9owUVvrmKjncKKTYzAkleuHx43pWq93T9bh1llhl/8EX1jOrVTsyTKRJkMgntD2vjPeDrZRGjQ="
    - secure: "BdRerctcHfM4b3TDWPtkeHTv6WP/GioMO5gw4podQOlEYXMxDhwVrf9wqC+eIDl9KS6+FSvOfrQvTuGKrWWTWoTiP+tBuJaKhfzALXl7PcKlwL3ThVlr+8GSsVA20XHBD2i2Hk0azenzX6cXv+NXtHdkCVoj6sld8tnQ0/8fZbY="

matrix:
  fast_finish: true
  # allow_failures:
  #           - env: "JOB=AppImage_x86_64"
  #           - env: "JOB=AppImage_i686"
  #           - env: "JOB=AppImage_armhf"
  #           - env: "JOB=MacOSX"

  include:
  # 1st parallel build job - debug build on Ubuntu
    - env: "JOB=Tests"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libsamplerate0-dev
            - libquazip0-dev
            - libsdl2-dev
      cache:
        directories:
          - $HOME/.ccache
      install:
        - "git fetch --unshallow"
        - "source ./ci/travis/linux-env.sh"
      script:
        - chmod +x "./ci/travis/linux-build.sh"
        - "./ci/travis/linux-build.sh"
      after_script:
        - cd install
        - export BUILD_TAG="Phoenix-travis${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:6}-Linux"
        - artifacts upload --target-paths /Linux/${BUILD_TAG} --working-dir `pwd` .

notifications:
  irc:
    channels:
      - "chat.freenode.net#phoenix-dev"
    use_notice: true
    skip_join: true

dist: trusty
git:
  submodules: false
